### ISSUE TITLE
A question from a newbie....

### ISSUE THREAD

**Issue by liakosgeo** [GeoPyTool/GeoPyTool#10]
### Bug report

**Bug summary**

**GeoPyTool version**

  * Operating system:
  * GeoPyTool version: 
  * Which function causes the error:
  * Other Information: 

  * 操作系统（精确到版本号）:
  * GeoPyTool 版本: 
  * 出错的功能:
  * 其他信息: 

  

  
  
**Data for reproduction**

**Actual outcome**

```
# If applicable, paste the console output or the Screenshot of terminal during the error here 
#
#
```

**Comment by liakosgeo** [comment]
Hello, at first, please forgive me for my unawareness because I am a newbie in github and programming concepts. Seems you worked hard on this app. Could you please give me hints on how I could create a new template diagram to load as basemap? I suppose I cannot do it straight from a paper and it needs some coding?

**Comment by liakosgeo** [comment]
Hello, at first, please forgive me for my unawareness because I am a newbie in github and programming concepts. Seems you worked hard on this app. Could you please give me hints on how I could create a new template diagram to load as basemap? I suppose I cannot do it straight from a paper and it needs some coding?

**Comment by cycleuser** [comment]
I have no access to download the article you pasted.
could you please send a copy of it here as a atachment? 
let me take a look at it please.

**Comment by cycleuser** [comment]
![Gibbs1（1970Gibbs-Mechanisms Controlling World Water Chemistry）](https://user-images.githubusercontent.com/6130092/66615159-25359580-ebfe-11e9-98b3-83904481b2cc.png)
![Gibbs2（1970Gibbs-Mechanisms Controlling World Water Chemistry）](https://user-images.githubusercontent.com/6130092/66615160-25359580-ebfe-11e9-8f21-0c828a0a9740.png)

**Comment by liakosgeo** [comment]
Thanks!
