### ISSUE TITLE
Issue while installing the geopytool in colab

### ISSUE THREAD

**Issue by algoRYT1-IM** [GeoPyTool/GeoPyTool#23]
### Bug report

**Bug summary**

**GeoPyTool version**

  * Operating system: Ubuntu 20.04
  * GeoPyTool version: 
  * Which function causes the error:
  * Other Information:  Sir I used google collab to instal geopytool and followed the instructions on the geopytool.com website. But while running the command "pip install geopytool" the  error "ERROR: Could not find a version that satisfies the requirement geopytool (from versions: 0.7.51, 0.7.52, 0.7.53, 0.7.54, 0.7.55, 0.7.56, 0.7.57, 0.7.58, 0.7.59, 0.7.60, 0.7.61, 0.7.62, 0.7.63, 0.7.64, 0.7.65, 0.7.66, 0.7.67, 0.7.68, 0.7.69, 0.7.70, 0.7.71, 0.7.72, 0.7.73, 0.7.74, 0.7.75, 0.7.76, 0.7.77, 0.7.78, 0.7.79, 0.7.80, 0.7.81, 0.7.82, 0.7.83, 0.7.84, 0.7.85, 0.7.86, 0.7.87, 0.7.88, 0.7.89, 0.7.90, 0.7.91, 0.7.92, 0.7.93, 0.7.94, 0.7.95, 0.7.96, 0.7.97, 0.7.98, 0.7.99, 0.8.0, 0.8.1, 0.8.2, 0.8.3, 0.8.4, 0.8.5, 0.8.6, 0.8.7, 0.8.9, 0.8.10, 0.8.11, 0.8.12, 0.8.13.10.28, 0.8.14.12.5, 0.8.19.1.1, 0.8.19.1.2, 0.8.19.1.4, 0.8.19.1.5, 0.8.19.1.9, 0.8.19.1.10, 0.8.19.1.12, 0.8.19.1.13, 0.8.19.1.14, 0.8.19.1.15, 0.8.19.1.16, 0.8.19.1.17, 0.8.19.1.18, 0.8.19.1.19, 0.8.19.1.20, 0.8.19.1.21, 0.8.19.1.22, 0.8.19.1.23, 0.8.19.1.24, 0.8.19.1.25, 0.8.19.1.26, 0.8.19.1.27, 0.8.19.1.28, 0.8.19.1.29, 0.8.19.1.30, 0.8.19.1.31, 0.8.19.1.32, 0.8.19.1.33, 0.8.19.1.34, 0.8.19.1.35, 0.8.19.1.36, 0.8.19.1.37, 0.8.19.1.38, 0.8.19.1.40, 0.8.19.1.41, 0.8.19.1.42, 0.8.19.1.43, 0.8.19.2.1, 0.8.19.3.1, 0.8.19.3.3, 0.8.19.3.4, 0.8.19.3.5, 0.8.19.3.6, 0.8.19.3.7, 0.8.19.3.8, 0.8.19.3.9, 0.8.19.3.91, 0.8.19.3.92, 0.8.19.3.93, 0.8.19.3.94, 0.8.19.3.95, 0.8.19.3.96, 0.8.19.3.97, 0.8.19.3.98, 0.8.19.3.99, 0.8.19.4.100, 0.8.19.4.101, 0.8.19.4.102, 0.8.19.4.103, 0.8.19.4.104, 0.8.19.4.105, 0.8.19.4.106, 0.8.19.4.107, 0.8.19.4.108, 0.8.19.5.100, 0.8.19.5.101, 0.8.19.5.102, 0.8.19.5.103, 0.8.19.5.104, 0.8.20.0.100, 0.8.20.0.101, 0.8.20.0.102, 0.8.20.0.103, 0.8.20.0.104, 0.8.20.0.105, 0.8.20.0.106, 0.8.20.0.107, 0.8.20.0.108, 0.8.20.0.109, 0.8.20.0.110, 0.8.20.0.111, 0.8.20.0.112, 0.8.20.0.113, 0.8.20.0.114, 0.8.20.0.115, 0.8.20.0.116, 0.8.20.0.117, 0.8.20.0.118, 0.8.20.0.119, 0.8.20.0.120, 0.8.20.0.121, 0.8.20.0.122, 0.8.20.0.123, 0.8.20.0.124, 0.8.20.0.125, 0.8.20.0.126, 0.8.20.0.127, 0.8.20.0.128, 0.8.20.0.129, 0.8.20.0.130, 0.8.20.0.131, 0.8.20.0.132, 0.8.20.0.133, 0.8.20.0.200, 0.8.20.0.202, 0.8.20.0.203, 0.8.20.0.204, 0.8.20.0.205, 0.9.21.0.1, 0.9.21.0.2, 0.9.21.0.3, 0.9.21.0.4, 0.9.21.0.5, 0.9.21.0.6, 0.9.21.0.7, 0.9.21.0.8, 0.9.21.0.9, 0.9.21.0.10, 0.9.21.0.11, 0.9.22.0.1)
ERROR: No matching distribution found for geopytool" occurred. I don't know how to proceed. It would be really helpful if you could instruct me. Thank you, sir 

  * 操作系统（精确到版本号）:
  * GeoPyTool 版本: 
  * 出错的功能:
  * 其他信息: 

  

  
  
**Data for reproduction**

**Actual outcome**

```
# If applicable, paste the console output or the Screenshot of terminal during the error here 
#
#
```

**Comment by cycleuser** [comment]
I got no Ubuntu 20.04 right now around. 
After receiving this issue, I have tested the installation as described at  http://geopytool.com/installation-expert.html and successfully installed it on a Ubuntu 22.04.

So maybe it would be something about the installation progress on your OS or maybe some problems on Ubuntu 20.04?

I got no idea about this right now.

**Comment by algoRYT1-IM** [comment]
Thank you for the replay sir
