### ISSUE TITLE
I tried to install geopython using pip in the command prompt, I went on properly but then the following message appear in the cmd

### ISSUE THREAD

**Issue by Abuobida** [GeoPyTool/GeoPyTool#3]
Command "c:\users\user\appdata\local\programs\python\python36-32\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\user\\AppData\\Local\\Temp\\pip-build-lftjfagv\\scikit-image\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\user\AppData\Local\Temp\pip-mrnd1c1i-record\install-record.txt --single-version-externally-managed --compile" failed with error code 1 in C:\Users\user\AppData\Local\Temp\pip-build-lftjfagv\scikit-image\

**Comment by Abuobida** [comment]
I guess the issue is that there is a need for having C++ 14 installed in the device ;this is according to this message:
error: Microsoft Visual C++ 14.0 is required. Get it with "Microsoft Visual C++ Build Tools": http://landinghub.visualstudio.com/visual-cpp-build-tools

**Comment by cycleuser** [comment]
This seems to be caused by the installation of scikit-image.
The link in the error message might help but there might also be some other problems to install scikit-image or sci-py.


My advice is to use the packed up App: http://doc.geopython.com/download.html

**Comment by cycleuser** [comment]
@Abuobida 

Another way to solve the problems of installing scikit and other related modules is to use conda.
for example:
1, use `pip install conda` to install conda  first.
2, run `python -m conda install scikit-learn numpy scipy` to install the required modules.
3, after the installation of needed modules mentioned above, run `pip install pyqtgraph` to install pyqtgraph.
4, now if there is nothing goes wrong, run `pip install geopython ` to install geopython.

Please leave a message here if you have any problems.

**Comment by cycleuser** [comment]
@Abuobida 

We have changed the name and domain of this project. Please use `pip install geopytool --upgrade` to install or update to latest version.
